import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "components/ThemeRegistry/ThemeRegistry";
import { CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ThemeRegistry>
          <CssBaseline>{children}</CssBaseline>
        </ThemeRegistry>
      </body>
    </html>
  );
}
